In [ ]:
import numpy as np

# 1.Python program to add two Matrices

In [8]:
import numpy as np
a = np.array([1,2,3,4,5,6])
b = np.array([7,8,9,10,11,12])
s = np.add(a,b)
s

array([ 8, 10, 12, 14, 16, 18])

# 2. Python program to multiply two matrices

In [12]:
a = np.array([[1,2],
              [3,4]])
b = np.array([[7,8],
              [10,11]])
m = a@b
m

array([[27, 30],
       [61, 68]])

# 3.	Python program for Matrix Product

In [ ]:
a = np.array([[1,2],
              [3,4]])
b = np.array([[7,8],
              [10,11]])
m = a@b
m

# 4.Adding and Subtracting Matrices in Python

In [15]:
a = np.array([[1,2],
              [3,4]])
b = np.array([[7,8],
              [10,11]])
t = np.add(a,b)
s = a - b
t,s

(array([[ 8, 10],
        [13, 15]]),
 array([[-6, -6],
        [-7, -7]]))

# 5.Transpose a matrix in Single line in Python

In [17]:
a = np.array([[1,2],
              [3,4]])
transpose = a.T
transpose

array([[1, 3],
       [2, 4]])

# 6.Python  Matrix creation of n*n

In [19]:
m = np.arange(0,20).reshape(4,5)
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

# 7.Python -- Get Kth Column of Matrix

In [23]:
m = np.arange(0,20).reshape(4,5)
print(m)
m[:,0]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


array([ 0,  5, 10, 15])

# 8.Python – Vertical Concatenation in Matrix

In [26]:
a = np.array([[1,2],
              [3,4]])
b = np.array([[7,8],
              [10,11]])
v_s = np.vstack((a,b))
v_s

array([[ 1,  2],
       [ 3,  4],
       [ 7,  8],
       [10, 11]])

# 9.Python program to check if a string is palindrome or not

In [33]:
s = input('Enter a string :')

if s == s[::-1]:
    print('String is a Palindrome')
else:
    print('String is Not a Palindrome')
    

Enter a string :abba
String is a Palindrome


# 10.Python program to check whether the string is Symmetrical or Palindrome

In [34]:
s = input('Enter a string :')

if s == s[::-1]:
    print('String is a Palindrome')
else:
    print('String is Not a Palindrome')
    

Enter a string :1221
String is a Palindrome
